{% set version = '3.0.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-poolfstat
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/poolfstat_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/poolfstat/poolfstat_{{ version }}.tar.gz
  sha256: 299cb6787c3a3ccccc4555bc9f87a02eb0c882ea478f31f1fb8abfbf2a59e0dc

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - {{ stdlib("c") }}
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-diagrammer
    - r-matrix
    - r-rcpp >=1.0.5
    - r-rcppprogress
    - r-ryacas
    - r-ape
    - r-data.table
    - r-doparallel
    - r-foreach
    - r-nnls
    - r-progress
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-diagrammer
    - r-matrix
    - r-rcpp >=1.0.5
    - r-rcppprogress
    - r-ryacas
    - r-ape
    - r-data.table
    - r-doparallel
    - r-foreach
    - r-nnls
    - r-progress

test:
  commands:
    - $R -e "library('poolfstat')"           # [not win]
    - "\"%R%\" -e \"library('poolfstat')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=poolfstat
  license: GPL-2.0-or-later
  summary: Functions for the computation of F-, f- and D-statistics (e.g., Fst, hierarchical
    F-statistics, Patterson's F2, F3, F3*, F4 and D parameters) in population genomics
    studies from allele count or Pool-Seq read count data and for the fitting, building
    and visualization of admixture graphs. The package also includes several utilities
    to manipulate Pool-Seq data stored in standard format (e.g., such as 'vcf' files
    or 'rsync' files generated by the the 'PoPoolation' software) and perform conversion
    to alternative format (as used in the 'BayPass' and 'SelEstim' software). As of
    version 2.0, the package also includes utilities to manipulate standard allele count
    data (e.g., stored in TreeMix, BayPass and SelEstim format).
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
    - mhoban

# Package: poolfstat
# Authors@R: person(given = "Mathieu",family = "Gautier",role = c("aut", "cre"),email = "mathieu.gautier@inrae.fr")
# Version: 3.0.0
# License: GPL (>= 2)
# Title: Computing f-Statistics and Building Admixture Graphs Based on Allele Count or Pool-Seq Read Count Data
# Description: Functions for the computation of F-, f- and D-statistics (e.g., Fst, hierarchical F-statistics, Patterson's F2, F3, F3*, F4 and D parameters) in population genomics studies from allele count or Pool-Seq read count data and for the fitting, building and visualization of admixture graphs. The package also includes several utilities to manipulate Pool-Seq data stored in standard format (e.g., such as 'vcf' files or 'rsync' files generated by the the 'PoPoolation' software) and perform conversion to alternative format (as used in the 'BayPass' and 'SelEstim' software). As of version 2.0, the package also includes utilities to manipulate standard allele count data (e.g., stored in TreeMix, BayPass and SelEstim format).
# LinkingTo: Rcpp, RcppProgress
# Imports: Rcpp (>= 1.0.5), methods, data.table, utils, foreach, doParallel, parallel, DiagrammeR, ape, stats, Ryacas, Matrix, RcppProgress, progress, nnls
# Depends: R (>= 3.0)
# Encoding: UTF-8
# RoxygenNote: 7.3.2
# NeedsCompilation: yes
# Packaged: 2024-11-23 10:00:13 UTC; mathieu
# Author: Mathieu Gautier [aut, cre]
# Maintainer: Mathieu Gautier <mathieu.gautier@inrae.fr>
# Repository: CRAN
# Date/Publication: 2024-11-23 15:20:06 UTC
